// resources/js/Pages/Admin/Documents/Show.vue
<template>
  <AdminLayout>
    <template #header>
      <div class="flex items-center justify-between">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
          Detalhes do Documento
        </h2>
        <div class="flex space-x-4">
          <Link
            :href="route('admin.documents.edit', document.id)"
            class="px-4 py-2 text-sm font-medium text-white bg-yellow-600 rounded-md hover:bg-yellow-700"
          >
            Editar
          </Link>
          <Link
            :href="route('admin.documents.download', document.id)"
            class="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-md hover:bg-green-700"
          >
            Download
          </Link>
          <button
            @click="deleteDocument"
            class="px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-md hover:bg-red-700"
          >
            Excluir
          </button>
        </div>
      </div>
    </template>

    <div class="py-12">
      <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <!-- Detalhes do Documento -->
        <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
          <div class="p-6">
            <h3 class="mb-4 text-lg font-medium text-gray-900">
              Informações do Documento
            </h3>
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
              <div>
                <p class="text-sm font-medium text-gray-500">Título</p>
                <p class="mt-1 text-sm text-gray-900">{{ document.title }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Categoria</p>
                <p class="mt-1 text-sm text-gray-900">{{ document.category }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Criado por</p>
                <p class="mt-1 text-sm text-gray-900">{{ document.createdBy?.name }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Visibilidade</p>
                <p class="mt-1">
                  <span :class="[
                    'px-2 inline-flex text-xs leading-5 font-semibold rounded-full',
                    document.is_public ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                  ]">
                    {{ document.is_public ? 'Público' : 'Privado' }}
                  </span>
                </p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Criado em</p>
                <p class="mt-1 text-sm text-gray-900">
                  {{ new Date(document.created_at).toLocaleDateString('pt-BR') }}
                </p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Última atualização</p>
                <p class="mt-1 text-sm text-gray-900">
                  {{ new Date(document.updated_at).toLocaleDateString('pt-BR') }}
                </p>
              </div>
            </div>
          </div>
        </div>

        <!-- Descrição -->
        <div class="mt-8 overflow-hidden bg-white shadow-sm sm:rounded-lg">
          <div class="p-6">
            <h3 class="mb-4 text-lg font-medium text-gray-900">
              Descrição
            </h3>
            <div class="prose max-w-none">
              {{ document.description }}
            </div>
          </div>
        </div>

        <!-- Histórico de Versões -->
        <div class="mt-8 overflow-hidden bg-white shadow-sm sm:rounded-lg">
          <div class="p-6">
            <h3 class="mb-4 text-lg font-medium text-gray-900">
              Histórico de Versões
            </h3>
            <div class="overflow-x-auto">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                      Versão
                    </th>
                    <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                      Atualizado por
                    </th>
                    <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                      Data
                    </th>
                    <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                      Ações
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <tr v-for="version in document.versions" :key="version.id">
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="text-sm font-medium text-gray-900">
                        v{{ version.version }}
                      </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="text-sm text-gray-900">{{ version.updatedBy?.name }}</div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="text-sm text-gray-900">
                        {{ new Date(version.created_at).toLocaleDateString('pt-BR') }}
                      </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="flex space-x-2">
                        <Link
                          :href="route('admin.documents.download-version', [document.id, version.id])"
                          class="text-blue-600 hover:text-blue-900"
                        >
                          Download
                        </Link>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </AdminLayout>
</template>

<script setup>
import AdminLayout from '@/Layouts/AdminLayout.vue'
import { Head, Link, useForm } from '@inertiajs/vue3'

const props = defineProps({
  document: {
    type: Object,
    required: true
  }
})

const deleteDocument = () => {
  if (confirm(`Tem certeza que deseja excluir o documento ${props.document.title}?`)) {
    useForm().delete(route('admin.documents.destroy', props.document.id))
  }
}
</script>

// resources/js/pages/Petitions/Show.tsx
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Bot, Calendar, Clock, Download, FileText, User } from 'lucide-react';

interface Petition {
    id: number;
    title: string;
    content: string;
    type: 'pre_cadastrada' | 'ia';
    created_at: string;
    legal_case: {
        id: number;
        client_name: string;
        case_number: string;
        benefit_type?: string;
    };
    user: {
        name: string;
    };
}

interface Props {
    petition: Petition;
}

export default function Show({ petition }: Props) {
    const formatDate = (dateString: string) => {
        return new Date(dateString).toLocaleDateString('pt-BR', {
            day: '2-digit',
            month: '2-digit',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    const getTypeBadge = (type: string) => {
        return type === 'pre_cadastrada' ? (
            <Badge variant="secondary" className="flex items-center gap-1">
                <FileText className="h-3 w-3" />
                Pré-cadastrada
            </Badge>
        ) : (
            <Badge variant="default" className="flex items-center gap-1">
                <Bot className="h-3 w-3" />
                IA
            </Badge>
        );
    };

    return (
        <AppLayout>
            <Head title={`Petição - ${petition.title}`} />

            <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
                <div className="mx-auto max-w-7xl p-4 sm:p-6">
                    {/* Header */}
                    <div className="mb-6">
                        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                            <div className="flex items-center gap-4">
                                <Link href={route('petitions.index')}>
                                    <Button variant="outline" size="sm">
                                        <ArrowLeft className="mr-2 h-4 w-4" />
                                        Voltar
                                    </Button>
                                </Link>
                                <div>
                                    <h1 className="flex items-center text-3xl font-bold">
                                        <FileText className="mr-2 inline-block" /> Visualizar Petição
                                    </h1>
                                    <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                                        Petição criada em {formatDate(petition.created_at)}
                                    </p>
                                </div>
                            </div>
                            <div className="flex items-center gap-2">
                                {getTypeBadge(petition.type)}
                                <Link href={route('petitions.download', petition.id)}>
                                    <Button>
                                        <Download className="mr-2 h-4 w-4" />
                                        Download
                                    </Button>
                                </Link>
                            </div>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-6 lg:grid-cols-4">
                        {/* Informações */}
                        <div className="space-y-4 lg:col-span-1">
                            <Card className="border-blue-200 bg-gradient-to-r from-blue-50 to-blue-100 dark:border-blue-700 dark:from-blue-900/20 dark:to-blue-800/20">
                                <CardHeader>
                                    <CardTitle className="flex items-center gap-2 text-lg">
                                        <User className="h-5 w-5 text-blue-600" />
                                        Informações do Cliente
                                    </CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <div>
                                        <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Nome do Cliente</label>
                                        <div className="text-sm font-medium text-gray-900 dark:text-white">{petition.legal_case.client_name}</div>
                                    </div>
                                    <div>
                                        <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Número do Caso</label>
                                        <div className="text-sm text-gray-600 dark:text-gray-400">{petition.legal_case.case_number}</div>
                                    </div>
                                    {petition.legal_case.benefit_type && (
                                        <div>
                                            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                                                Tipo de Benefício
                                            </label>
                                            <Badge variant="outline" className="text-xs">
                                                {petition.legal_case.benefit_type}
                                            </Badge>
                                        </div>
                                    )}
                                </CardContent>
                            </Card>

                            <Card className="border-green-200 bg-gradient-to-r from-green-50 to-green-100 dark:border-green-700 dark:from-green-900/20 dark:to-green-800/20">
                                <CardHeader>
                                    <CardTitle className="flex items-center gap-2 text-lg">
                                        <Clock className="h-5 w-5 text-green-600" />
                                        Detalhes da Petição
                                    </CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <div>
                                        <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Criado por</label>
                                        <div className="flex items-center gap-2 text-sm text-gray-900 dark:text-white">
                                            <User className="h-4 w-4" />
                                            {petition.user.name}
                                        </div>
                                    </div>
                                    <div>
                                        <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Data de Criação</label>
                                        <div className="flex items-center gap-2 text-sm text-gray-900 dark:text-white">
                                            <Calendar className="h-4 w-4" />
                                            {formatDate(petition.created_at)}
                                        </div>
                                    </div>
                                    <div>
                                        <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">Tipo de Petição</label>
                                        {getTypeBadge(petition.type)}
                                    </div>
                                </CardContent>
                            </Card>
                        </div>

                        {/* Conteúdo */}
                        <div className="lg:col-span-3">
                            <Card className="h-fit">
                                <CardHeader>
                                    <CardTitle className="flex items-center gap-2 text-lg">
                                        <FileText className="h-5 w-5 text-purple-600" />
                                        Conteúdo da Petição
                                    </CardTitle>
                                </CardHeader>
                                <CardContent>
                                    <div className="prose prose-sm dark:prose-invert max-w-none">
                                        <div className="overflow-x-auto rounded-lg border-2 border-gray-200 bg-white p-4 sm:p-6 dark:border-gray-700 dark:bg-gray-800">
                                            <pre className="font-mono text-sm leading-relaxed whitespace-pre-wrap">{petition.content}</pre>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
