// resources/js/pages/Companies/Edit.tsx
import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import AppLayout from '@/layouts/app-layout';
import { Company } from '@/types';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { ArrowLeft, Building2, Trash2 } from 'lucide-react';

interface Props {
    company: Company;
}

interface CompanyFormData {
    name: string;
    email: string;
    cnpj: string;
    phone: string;
    address: string;
    city: string;
    state: string;
    zip_code: string;
    plan: 'basic' | 'premium' | 'enterprise';
    max_users: number;
    max_cases: number;
    is_active: boolean;
    [key: string]: string | number | boolean;
}

export default function Edit({ company }: Props) {
    const { data, setData, put, processing, errors } = useForm<CompanyFormData>({
        name: company.name || '',
        email: company.email || '',
        cnpj: company.cnpj || '',
        phone: company.phone || '',
        address: company.address || '',
        city: company.city || '',
        state: company.state || '',
        zip_code: company.zip_code || '',
        plan: company.plan || 'basic',
        max_users: company.max_users || 5,
        max_cases: company.max_cases || 100,
        is_active: company.is_active || false,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        put(route('companies.update', company.id));
    };

    const handleDelete = () => {
        if (confirm('Tem certeza que deseja excluir esta empresa? Esta ação não pode ser desfeita.')) {
            router.delete(route('companies.destroy', company.id));
        }
    };

    const planLimits = {
        basic: { users: 5, cases: 100 },
        premium: { users: 10, cases: 500 },
        enterprise: { users: 50, cases: 2000 },
    };

    const handlePlanChange = (plan: 'basic' | 'premium' | 'enterprise') => {
        setData({
            ...data,
            plan,
            max_users: planLimits[plan].users,
            max_cases: planLimits[plan].cases,
        });
    };

    return (
        <AppLayout>
            <Head title={`Editar ${company.name}`} />

            <div className="container mx-auto py-6">
                <div className="mb-6">
                    <div className="mb-4 flex items-center gap-4">
                        <Link
                            href={route('companies.index')}
                            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
                        >
                            <ArrowLeft className="h-4 w-4" />
                            Voltar para Empresas
                        </Link>
                    </div>

                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="rounded-lg bg-primary/10 p-2">
                                <Building2 className="h-6 w-6 text-primary" />
                            </div>
                            <div>
                                <h1 className="text-2xl font-bold">Editar Empresa</h1>
                                <p className="text-muted-foreground">{company.name}</p>
                            </div>
                        </div>

                        <Button variant="destructive" size="sm" onClick={handleDelete} className="gap-2">
                            <Trash2 className="h-4 w-4" />
                            Excluir
                        </Button>
                    </div>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Informações Básicas</CardTitle>
                            <CardDescription>Dados principais da empresa</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                                <div className="space-y-2">
                                    <Label htmlFor="name">Nome da Empresa *</Label>
                                    <Input
                                        id="name"
                                        value={data.name}
                                        onChange={(e) => setData('name', e.target.value)}
                                        placeholder="Ex: Escritório de Advocacia Silva"
                                    />
                                    <InputError message={errors.name} />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="email">E-mail</Label>
                                    <Input
                                        id="email"
                                        type="email"
                                        value={data.email}
                                        onChange={(e) => setData('email', e.target.value)}
                                        placeholder="contato@empresa.com"
                                    />
                                    <InputError message={errors.email} />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="cnpj">CNPJ</Label>
                                    <Input
                                        id="cnpj"
                                        value={data.cnpj}
                                        onChange={(e) => setData('cnpj', e.target.value)}
                                        placeholder="00.000.000/0000-00"
                                    />
                                    <InputError message={errors.cnpj} />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="phone">Telefone</Label>
                                    <Input
                                        id="phone"
                                        value={data.phone}
                                        onChange={(e) => setData('phone', e.target.value)}
                                        placeholder="(11) 99999-9999"
                                    />
                                    <InputError message={errors.phone} />
                                </div>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="address">Endereço</Label>
                                <Textarea
                                    id="address"
                                    value={data.address}
                                    onChange={(e) => setData('address', e.target.value)}
                                    placeholder="Rua, número, complemento"
                                    rows={3}
                                />
                                <InputError message={errors.address} />
                            </div>

                            <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                                <div className="space-y-2">
                                    <Label htmlFor="city">Cidade</Label>
                                    <Input id="city" value={data.city} onChange={(e) => setData('city', e.target.value)} placeholder="São Paulo" />
                                    <InputError message={errors.city} />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="state">Estado</Label>
                                    <Input
                                        id="state"
                                        value={data.state}
                                        onChange={(e) => setData('state', e.target.value)}
                                        placeholder="SP"
                                        maxLength={2}
                                    />
                                    <InputError message={errors.state} />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="zip_code">CEP</Label>
                                    <Input
                                        id="zip_code"
                                        value={data.zip_code}
                                        onChange={(e) => setData('zip_code', e.target.value)}
                                        placeholder="00000-000"
                                    />
                                    <InputError message={errors.zip_code} />
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>Plano e Limites</CardTitle>
                            <CardDescription>Configure o plano e limites de uso da empresa</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                                <div className="space-y-2">
                                    <Label htmlFor="plan">Plano *</Label>
                                    <Select value={data.plan} onValueChange={handlePlanChange}>
                                        <SelectTrigger>
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="basic">Básico (5 usuários, 100 casos)</SelectItem>
                                            <SelectItem value="premium">Premium (10 usuários, 500 casos)</SelectItem>
                                            <SelectItem value="enterprise">Enterprise (50 usuários, 2000 casos)</SelectItem>
                                        </SelectContent>
                                    </Select>
                                    <InputError message={errors.plan} />
                                </div>

                                <div className="flex items-center space-x-2">
                                    <Switch id="is_active" checked={data.is_active} onCheckedChange={(checked) => setData('is_active', checked)} />
                                    <Label htmlFor="is_active">Empresa Ativa</Label>
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="max_users">Máximo de Usuários *</Label>
                                    <Input
                                        id="max_users"
                                        type="number"
                                        min="1"
                                        max="1000"
                                        value={data.max_users}
                                        onChange={(e) => setData('max_users', parseInt(e.target.value) || 1)}
                                    />
                                    <InputError message={errors.max_users} />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="max_cases">Máximo de Casos *</Label>
                                    <Input
                                        id="max_cases"
                                        type="number"
                                        min="1"
                                        max="10000"
                                        value={data.max_cases}
                                        onChange={(e) => setData('max_cases', parseInt(e.target.value) || 1)}
                                    />
                                    <InputError message={errors.max_cases} />
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    <div className="flex items-center gap-4">
                        <Button type="submit" disabled={processing}>
                            {processing ? 'Salvando...' : 'Salvar Alterações'}
                        </Button>

                        <Link
                            href={route('companies.index')}
                            className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium ring-offset-background transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50"
                        >
                            Cancelar
                        </Link>
                    </div>
                </form>
            </div>
        </AppLayout>
    );
}

// resources/js/Pages/Admin/Companies/Edit.vue
<template>
  <AdminLayout :title="`Editar ${company.name}`">
    <template #header>
      <h2 class="text-xl font-semibold leading-tight text-gray-800">
        Editar {{ company.name }}
      </h2>
    </template>

    <div class="py-12">
      <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
          <div class="p-6">
            <form @submit.prevent="submit">
              <!-- Dados da Empresa -->
              <div class="mb-8">
                <h3 class="mb-4 text-lg font-medium text-gray-900">Dados da Empresa</h3>
                
                <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
                  <!-- Nome -->
                  <div>
                    <InputLabel for="name" value="Nome" />
                    <TextInput
                      id="name"
                      v-model="form.name"
                      type="text"
                      class="block w-full mt-1"
                      required
                    />
                    <InputError :message="form.errors.name" class="mt-2" />
                  </div>

                  <!-- Email -->
                  <div>
                    <InputLabel for="email" value="Email" />
                    <TextInput
                      id="email"
                      v-model="form.email"
                      type="email"
                      class="block w-full mt-1"
                      required
                    />
                    <InputError :message="form.errors.email" class="mt-2" />
                  </div>

                  <!-- CNPJ -->
                  <div>
                    <InputLabel for="cnpj" value="CNPJ" />
                    <TextInput
                      id="cnpj"
                      v-model="form.cnpj"
                      type="text"
                      class="block w-full mt-1"
                      v-maska="'##.###.###/####-##'"
                    />
                    <InputError :message="form.errors.cnpj" class="mt-2" />
                  </div>

                  <!-- Status -->
                  <div>
                    <InputLabel for="is_active" value="Status" />
                    <select
                      id="is_active"
                      v-model="form.is_active"
                      class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
                      required
                    >
                      <option :value="true">Ativa</option>
                      <option :value="false">Inativa</option>
                    </select>
                    <InputError :message="form.errors.is_active" class="mt-2" />
                  </div>

                  <!-- Limite de Usuários -->
                  <div>
                    <InputLabel for="max_users" value="Limite de Usuários" />
                    <TextInput
                      id="max_users"
                      v-model="form.max_users"
                      type="number"
                      class="block w-full mt-1"
                      required
                      min="1"
                    />
                    <InputError :message="form.errors.max_users" class="mt-2" />
                  </div>

                  <!-- Limite de Processos -->
                  <div>
                    <InputLabel for="max_cases" value="Limite de Processos" />
                    <TextInput
                      id="max_cases"
                      v-model="form.max_cases"
                      type="number"
                      class="block w-full mt-1"
                      required
                      min="1"
                    />
                    <InputError :message="form.errors.max_cases" class="mt-2" />
                  </div>
                </div>
              </div>

              <!-- Usuários -->
              <div class="mb-8">
                <div class="flex items-center justify-between mb-4">
                  <h3 class="text-lg font-medium text-gray-900">Usuários</h3>
                  <Link
                    :href="route('admin.users.create', { company_id: company.id })"
                    class="text-sm text-blue-600 hover:text-blue-900"
                  >
                    Adicionar Usuário
                  </Link>
                </div>

                <div class="overflow-x-auto">
                  <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                      <tr>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                          Nome
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                          Email
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                          Função
                        </th>
                        <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                          Status
                        </th>
                        <th scope="col" class="relative px-6 py-3">
                          <span class="sr-only">Ações</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                      <tr v-for="user in company.users" :key="user.id">
                        <td class="px-6 py-4 whitespace-nowrap">
                          <div class="text-sm font-medium text-gray-900">
                            {{ user.name }}
                          </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                          <div class="text-sm text-gray-900">{{ user.email }}</div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                          <div class="text-sm text-gray-900">
                            {{ user.role === 'admin' ? 'Administrador' : 'Usuário' }}
                          </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                          <span :class="[
                            'px-2 inline-flex text-xs leading-5 font-semibold rounded-full',
                            user.is_active ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                          ]">
                            {{ user.is_active ? 'Ativo' : 'Inativo' }}
                          </span>
                        </td>
                        <td class="px-6 py-4 text-sm font-medium text-right whitespace-nowrap">
                          <Link :href="route('admin.users.edit', user.id)" class="text-blue-600 hover:text-blue-900">
                            Editar
                          </Link>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <!-- Botões -->
              <div class="flex items-center justify-end mt-6">
                <Link
                  :href="route('admin.companies.index')"
                  class="text-gray-600 underline hover:text-gray-900"
                >
                  Cancelar
                </Link>

                <PrimaryButton
                  class="ml-4"
                  :class="{ 'opacity-25': form.processing }"
                  :disabled="form.processing"
                >
                  Salvar Alterações
                </PrimaryButton>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </AdminLayout>
</template>

<script setup>
import AdminLayout from '@/Layouts/AdminLayout.vue'
import { Link, useForm } from '@inertiajs/vue3'
import InputLabel from '@/Components/InputLabel.vue'
import TextInput from '@/Components/TextInput.vue'
import InputError from '@/Components/InputError.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'
import { vMaska } from 'maska'

const props = defineProps({
  company: {
    type: Object,
    required: true
  }
})

const form = useForm({
  name: props.company.name,
  email: props.company.email,
  cnpj: props.company.cnpj,
  is_active: props.company.is_active,
  max_users: props.company.max_users,
  max_cases: props.company.max_cases
})

function submit() {
  form.put(route('admin.companies.update', props.company.id))
}
</script>

<script>
export default {
  directives: { maska: vMaska }
}
</script>
