// resources/js/Layouts/AdminLayout.vue
<template>
  <div>
    <Head :title="title" />

    <div class="min-h-screen bg-gray-100">
      <!-- Barra de navegação superior -->
      <nav class="bg-white border-b border-gray-100">
        <div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
          <div class="flex justify-between h-16">
            <div class="flex">
              <!-- Logo -->
              <div class="flex items-center shrink-0">
                <Link :href="route('admin.dashboard')">
                  <ApplicationLogo class="block w-auto h-9" />
                </Link>
              </div>

              <!-- Links de Navegação -->
              <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                <NavLink :href="route('admin.dashboard')" :active="route().current('admin.dashboard')">
                  Dashboard
                </NavLink>
                <NavLink :href="route('admin.companies.index')" :active="route().current('admin.companies.*')">
                  Empresas
                </NavLink>
                <NavLink :href="route('admin.users.index')" :active="route().current('admin.users.*')">
                  Usuários
                </NavLink>
                <NavLink :href="route('admin.documents.index')" :active="route().current('admin.documents.*')">
                  Base de Conhecimento
                </NavLink>
              </div>
            </div>

            <!-- Menu do Usuário -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
              <div class="relative ml-3">
                <Dropdown align="right" width="48">
                  <template #trigger>
                    <span class="inline-flex rounded-md">
                      <button type="button" class="inline-flex items-center px-3 py-2 text-sm font-medium leading-4 text-gray-500 transition duration-150 ease-in-out bg-white border border-transparent rounded-md hover:text-gray-700 focus:outline-none">
                        {{ $page.props.auth.user.name }}
                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                          <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                        </svg>
                      </button>
                    </span>
                  </template>

                  <template #content>
                    <DropdownLink :href="route('profile.edit')">
                      Perfil
                    </DropdownLink>
                    <DropdownLink :href="route('logout')" method="post" as="button">
                      Sair
                    </DropdownLink>
                  </template>
                </Dropdown>
              </div>
            </div>

            <!-- Botão do Menu Mobile -->
            <div class="flex items-center -mr-2 sm:hidden">
              <button @click="showingNavigationDropdown = !showingNavigationDropdown" class="inline-flex items-center justify-center p-2 text-gray-400 transition duration-150 ease-in-out rounded-md hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500">
                <svg class="w-6 h-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                  <path :class="{'hidden': showingNavigationDropdown, 'inline-flex': !showingNavigationDropdown}" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  <path :class="{'hidden': !showingNavigationDropdown, 'inline-flex': showingNavigationDropdown}" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        <!-- Menu Mobile -->
        <div :class="{'block': showingNavigationDropdown, 'hidden': !showingNavigationDropdown}" class="sm:hidden">
          <div class="pt-2 pb-3 space-y-1">
            <ResponsiveNavLink :href="route('admin.dashboard')" :active="route().current('admin.dashboard')">
              Dashboard
            </ResponsiveNavLink>
            <ResponsiveNavLink :href="route('admin.companies.index')" :active="route().current('admin.companies.*')">
              Empresas
            </ResponsiveNavLink>
            <ResponsiveNavLink :href="route('admin.users.index')" :active="route().current('admin.users.*')">
              Usuários
            </ResponsiveNavLink>
            <ResponsiveNavLink :href="route('admin.documents.index')" :active="route().current('admin.documents.*')">
              Base de Conhecimento
            </ResponsiveNavLink>
          </div>

          <!-- Menu Mobile do Usuário -->
          <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
              <div class="text-base font-medium text-gray-800">
                {{ $page.props.auth.user.name }}
              </div>
              <div class="text-sm font-medium text-gray-500">
                {{ $page.props.auth.user.email }}
              </div>
            </div>

            <div class="mt-3 space-y-1">
              <ResponsiveNavLink :href="route('profile.edit')">
                Perfil
              </ResponsiveNavLink>
              <ResponsiveNavLink :href="route('logout')" method="post" as="button">
                Sair
              </ResponsiveNavLink>
            </div>
          </div>
        </div>
      </nav>

      <!-- Cabeçalho da Página -->
      <header class="bg-white shadow" v-if="$slots.header">
        <div class="px-4 py-6 mx-auto max-w-7xl sm:px-6 lg:px-8">
          <slot name="header" />
        </div>
      </header>

      <!-- Conteúdo da Página -->
      <main>
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { Head, Link } from '@inertiajs/vue3'
import ApplicationLogo from '@/Components/ApplicationLogo.vue'
import Dropdown from '@/Components/Dropdown.vue'
import DropdownLink from '@/Components/DropdownLink.vue'
import NavLink from '@/Components/NavLink.vue'
import ResponsiveNavLink from '@/Components/ResponsiveNavLink.vue'

const showingNavigationDropdown = ref(false)

defineProps({
  title: {
    type: String,
    default: ''
  }
})
</script>

// resources/js/Layouts/AdminLayout.tsx
import React from 'react';
import { Link, usePage } from '@inertiajs/react';
import { User } from '@/types';
import { Building2, Users, FileText, GitBranch, Settings, LogOut } from 'lucide-react';

interface Props {
  children: React.ReactNode;
}

const AdminLayout: React.FC<Props> = ({ children }) => {
  const { auth } = usePage().props as { auth: { user: User } };

  const menuItems = [
    {
      name: 'Dashboard',
      href: route('admin.dashboard'),
      icon: <Building2 className="w-5 h-5" />,
    },
    {
      name: 'Empresas',
      href: route('admin.companies.index'),
      icon: <Building2 className="w-5 h-5" />,
    },
    {
      name: 'Usuários',
      href: route('admin.users.index'),
      icon: <Users className="w-5 h-5" />,
    },
    {
      name: 'Documentos',
      href: route('admin.documents.index'),
      icon: <FileText className="w-5 h-5" />,
    },
    {
      name: 'Templates',
      href: route('admin.templates.index'),
      icon: <GitBranch className="w-5 h-5" />,
    },
    {
      name: 'Configurações',
      href: route('admin.settings.index'),
      icon: <Settings className="w-5 h-5" />,
    },
  ];

  return (
    <div className="min-h-screen bg-gray-100">
      {/* Sidebar */}
      <div className="fixed inset-y-0 left-0 z-50 w-64 bg-white border-r border-gray-200">
        <div className="flex flex-col h-full">
          {/* Logo */}
          <div className="flex items-center justify-center h-16 px-4 border-b border-gray-200">
            <Link href={route('admin.dashboard')} className="text-xl font-bold text-gray-900">
              Previdia Admin
            </Link>
          </div>

          {/* Navigation */}
          <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
            {menuItems.map((item) => (
              <Link
                key={item.name}
                href={item.href}
                className={`flex items-center px-4 py-2 text-sm font-medium rounded-lg ${
                  route().current(item.href)
                    ? 'bg-gray-100 text-gray-900'
                    : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                }`}
              >
                {item.icon}
                <span className="ml-3">{item.name}</span>
              </Link>
            ))}
          </nav>

          {/* User */}
          <div className="p-4 border-t border-gray-200">
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-gray-500">
                  <span className="text-sm font-medium leading-none text-white">
                    {auth.user.name[0]}
                  </span>
                </span>
              </div>
              <div className="ml-3">
                <p className="text-sm font-medium text-gray-900">{auth.user.name}</p>
                <p className="text-xs font-medium text-gray-500">{auth.user.email}</p>
              </div>
              <Link
                href={route('logout')}
                method="post"
                as="button"
                className="p-2 ml-auto text-gray-400 rounded-md hover:text-gray-500 hover:bg-gray-100"
              >
                <LogOut className="w-5 h-5" />
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="pl-64">
        <main className="py-12">
          <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
};

export default AdminLayout;
